main: "com.act.timer.ActTimer"
name: "Act-Timer"
version: "1.0"
api-version: "1.20"

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.22

commands:
  timer:
    permission: "act.admin"
    description: "Timer Command"
    aliases:
      - 타이머
    usage: "/<command> [시작/중단/끄기]"